2022-01-23 13:38:10,627 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 13:43:37,689 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:03:04,692 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:03:12,970 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:06:28,772 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:06:52,606 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:08:17,579 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:23:34,775 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:31:22,883 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:32:14,853 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:32:31,588 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:40:23,902 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:40:35,554 ERROR: Exception on /user/sarah [GET] [in /home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/adam/PycharmProjects/flaskProject/app/routes.py", line 80, in user
    return render_template("user.html", user=user, posts=posts)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/adam/PycharmProjects/flaskProject/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/adam/PycharmProjects/flaskProject/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/adam/PycharmProjects/flaskProject/app/templates/user.html", line 14, in block 'content'
    {% elif not current_user.is_following(user) %}
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/utils.py", line 84, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'is_following'
2022-01-23 15:41:00,899 INFO: Microblog startup [in /home/adam/PycharmProjects/flaskProject/app/__init__.py:52]
2022-01-23 15:41:19,787 ERROR: Exception on /user/sarah [GET] [in /home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/adam/PycharmProjects/flaskProject/app/routes.py", line 80, in user
    return render_template("user.html", user=user, posts=posts)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/adam/PycharmProjects/flaskProject/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/adam/PycharmProjects/flaskProject/app/templates/base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "/home/adam/PycharmProjects/flaskProject/app/templates/user.html", line 17, in block 'content'
    {{ form.hidden_tag() }}
  File "/home/adam/.local/share/virtualenvs/flaskProject-qi1PJiJv/lib/python3.10/site-packages/jinja2/environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
